dev_addr: !ENV [ESDOC_TECH_DEV_ADDR, 127.0.0.1:8000]

nav:
  - Home: "index.md"

  - Archives:
    - CDF2CIM: "archives/cdf2cim.md"
    - Documentation: "archives/documentation.md"
    - PYESSV: "archives/pyessv.md"

  - Libraries:
    - PYESSV: "libs/pyessv.md"
    - PYESDOC: "libs/pyesdoc.md"

  - Schemas:
    - CIM Ontology: "schemas/ontology.md"
    - Specialisations: "schemas/specialisations.md"

  - Web APIs:
    - CDF2CIM: "web-apis/cdf2cim.md"
    - Documentation: "web-apis/documentation.md"
    - Errata: "https://es-doc.github.io/esdoc-errata-client"
    - PYESSV: "web-apis/pyessv.md"

  - Web Applications:
    - Comparator: "front-ends/comparator.md"
    - Errata: "https://es-doc.github.io/esdoc-errata-client"
    - Explorer: "front-ends/explorer.md"
    - Search: "front-ends/search.md"
    - Specialisations: "front-ends/specialisations.md"

  - CLI Applications:
    - Main: "shells/main.md"
    - CMIP6: "shells/cmip6.md"
    - CORDEX: "shells/cordex.md"

  - Dev Ops:
    - OpalStack:
      - Servers: "devops/servers.md"
      - Troubleshooting: "devops/troubleshooting.md"
    - Installers:
      - Web APIs:
        - Errata: "installers/ws-errata.md"
        - PYESSV: "installers/ws-pyessv.md"

site_name: ES-DOC Technical Documentation

theme:
    name: material
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    highlightjs: true
    feature:
        - navigation.tabs

markdown_extensions:
    - toc:
        permalink: True
